### ISSUE TITLE
How to use UART GPS on Raspberry Pi?

### ISSUE THREAD

**Issue by mash55** [jantman/pizero-gpslog#4]
Thanks for the write-up and code. How/where do I (re)configure pizero-gpslog to use UART instead of a USB gps?

**Comment by ar4121** [comment]
I'm not 100% positive, but just skimming the code on my phone, it looks like it basically polls gpsd for the data. 

Are you able to get a good GPS fix and read out the NMEA data with your GPS device otherwise?

The dev is pretty responsive.

**Comment by ar4121** [comment]
It won't let me edit for some reason... I just read the Readme.rst which would have saved me from looking all in the runner.py code, the program relies on gpsd.  

Is gpsd functional on your pi?

**Comment by jantman** [comment]
@mash55 @ar4121 Yes, pizero-gpslog relies on [gpsd](http://www.catb.org/gpsd/). I have Raspbian Stretch on my pi, and gpsd is available directly from the repositories.

As I mention in the [README](https://github.com/jantman/pizero-gpslog/blob/master/README.rst):

> This program relies on gpsd to interact with the GPS itself, as it's very mature and stable software, exposes a simple JSON-based socket interface, and also has decent Python bindings. There's no reason for a logger to have to worry about the nuances of GPS communication itself.

The [hardware compatibility list for gpsd](http://www.catb.org/gpsd/hardware.html) _does_ list some UART GPSes as being compatible, in addition to some RaspberryPi-specific models. So you might have some luck getting it to work. Docs on gpsd are [here](http://www.catb.org/gpsd/#documentation) and they also have an IRC channel, [#gpsd on freenode](irc://irc.freenode.net#gpsd). I'd pay special attention to [gpsmon](http://www.catb.org/gpsd/gpsmon.html), [gpspipe](http://www.catb.org/gpsd/gpspipe.html), and [gpscat](http://www.catb.org/gpsd/gpscat.html) for troubleshooting.

Note also that the [gpsd man page](http://www.catb.org/gpsd/gpsd.html) contains the following, which gives a hint that it might work:

> /dev/ttyAMA0
> The UART device on a Raspberry Pi. Has the side effect of opening /dev/pps0 for RFC2783 1PPS data.

**Comment by mash55** [comment]
Thanks guys, it's working now. The default config for gpsd is not working with the UART gps on my pi. After changing the /etc/default/gpsd file to use the UART serial port everything started to work. Appreciate the quick responses...

**Comment by jantman** [comment]
@mash55 ok, I'm glad you got it working.

Do you think this issue can be closed as resolved at this point?

**Comment by mash55** [comment]
yep, issue is resolved

**Comment by jantman** [comment]
Ok, thanks!
