### ISSUE TITLE
no logfile created ? 

### ISSUE THREAD

**Issue by edegraaff** [jantman/pizero-gpslog#8]
Hi, i have installed the project, my usb gps dongle is working, all seems ok, but i have no tracking files. 
What could cause this ? 

Regards

Eelco

**Comment by jantman** [comment]
Is the daemon running? Have you tried running it in the foreground, with LOG_LEVEL=DEBUG, and seeing what the log messages are? Do you  have either a display or LEDs installed, and if so, do they give indication of a position fix?

**Comment by jantman** [comment]
@edegraaff Sorry, that reply was rather quick, and made a lot of assumptions.

How much experience do you have with Python, or with Linux in general? Does any of the above make sense to you?

I'm actually about to go on a short morning hike, but if it will help, I can add a more detailed troubleshooting section to the README file later today.

In the mean time, assuming you installed it according to the instructions and have some sort of command-line access to your running pi (either SSH or actual keyboard/monitor), the output of `sudo systemctl status pizero-gpslog` and `sudo journalctl -u pizero-gpslog -e` would be my first places to check. If you can post the output of those, I should be able to help.

Also please note that, if I remember correctly, I don't think the tracking files are written until the GPS has a fix. So make sure that it has a clear view of the sky, and if the GPS has been turned off for more than a few days, note that it could take some time for it to establish a "cold fix".

**Comment by edegraaff** [comment]
> Is the daemon running? Have you tried running it in the foreground, with LOG_LEVEL=DEBUG, and seeing what the log messages are? Do you have either a display or LEDs installed, and if so, do they give indication of a position fix?

Hi 
Thanks for your quick response. Yes i did check all logfilesm and installed twice in a clean raspbian image. First time i made the error to add also the screen driver part. Second install i checked the logs, all seems to be ok, and the demon started every 10 seconds. I also tried de option to get an debug log. Strange enough i did not get any usable info. I installed cgps and tested cgps -s and i got readings at right location. 
I will reinstall again, and check all logs. I am a system administrator and not a programmer:-)

**Comment by edegraaff** [comment]
I made the whole procedure again, and also there, are errors in the log ... thats obvious... reason is for me a bit unclear, missing modules ?

 
System info 

Pi 1
Raspbian Linux 32 bit 10 Buster
Kernel 5.10.11

USB GPS dongle active as ttyAMA0 recognised

hostname set, timezone set, keyboard set, passw set


Installation:
sudo apt-get update && sudo apt-get install haveged git python3-gpiozero python3-setuptools python3-pip gpsd python-gps

Installs python 3.7 

During install no errors 

Fetched 13.1 MB in 44s (294 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  dh-python gir1.2-glib-2.0 git-man libbluetooth3 libcurl3-gnutls
  liberror-perl libexpat1-dev libgirepository-1.0-1 libgps23 libhavege1
  libpython3-dev libpython3.7-dev python-pip-whl python3-asn1crypto
  python3-cffi-backend python3-colorzero python3-crypto python3-cryptography
  python3-dbus python3-dev python3-distutils python3-entrypoints python3-gi
  python3-keyring python3-keyrings.alt python3-lib2to3 python3-rpi.gpio
  python3-secretstorage python3-spidev python3-wheel python3-xdg python3.7-dev
Suggested packages:
  git-daemon-run | git-daemon-sysvinit git-doc git-el git-email git-gui gitk
  gitweb git-cvs git-mediawiki git-svn gpsd-clients apparmor python-crypto-doc
  python-cryptography-doc python3-cryptography-vectors python-dbus-doc
  python3-dbus-dbg python-gpiozero-docs gnome-keyring libkf5wallet-bin
  gir1.2-gnomekeyring-1.0 python-secretstorage-doc python-setuptools-doc
  python-spidev-doc
The following NEW packages will be installed:
  dh-python gir1.2-glib-2.0 git git-man gpsd haveged libbluetooth3
  libcurl3-gnutls liberror-perl libexpat1-dev libgirepository-1.0-1 libgps23
  libhavege1 libpython3-dev libpython3.7-dev python-gps python-pip-whl
  python3-asn1crypto python3-cffi-backend python3-colorzero python3-crypto
  python3-cryptography python3-dbus python3-dev python3-distutils
  python3-entrypoints python3-gi python3-gpiozero python3-keyring
  python3-keyrings.alt python3-lib2to3 python3-pip python3-rpi.gpio
  python3-secretstorage python3-setuptools python3-spidev python3-wheel
  python3-xdg python3.7-dev


Then
sudo pip3 install pizero-gpslog && sudo pizero-gpslog-install
  Downloading https://files.pythonhosted.org/packages/6d/4f/6f1317d7d024f32410ff14cd31d4a164c7ac82ecedd34a5d6143500f7b6f/pizero_gpslog-1.1.0-py2.py3-none-any.whl (646kB)
    100% |████████████████████████████████| 655kB 78kB/s
Collecting pillow (from pizero-gpslog)
  Downloading https://www.piwheels.org/simple/pillow/Pillow-8.1.0-cp37-cp37m-linux_armv6l.whl (1.3MB)
    100% |████████████████████████████████| 1.3MB 36kB/s
Requirement already satisfied: gpiozero in /usr/lib/python3/dist-packages (from pizero-gpslog) (1.5.1)
Collecting pint (from pizero-gpslog)
  Downloading https://files.pythonhosted.org/packages/5f/0e/dd4fb17aed6bfbc168fd767cffb6ec20b634009b75fd8ea699ea244bff3c/Pint-0.16.1-py2.py3-none-any.whl (205kB)
    100% |████████████████████████████████| 215kB 195kB/s
Collecting gpxpy (from pizero-gpslog)
  Downloading https://www.piwheels.org/simple/gpxpy/gpxpy-1.4.2-py3-none-any.whl (42kB)
    100% |████████████████████████████████| 51kB 373kB/s
Collecting importlib-metadata; python_version < "3.8" (from pint->pizero-gpslog)
  Downloading https://files.pythonhosted.org/packages/f3/ed/da40116a204abb5c4dd1d929346d33e0d29cedb2cedd18ea98f0385dcd92/importlib_metadata-3.4.0-py3-none-any.whl
Collecting packaging (from pint->pizero-gpslog)
  Downloading https://files.pythonhosted.org/packages/3e/89/7ea760b4daa42653ece2380531c90f64788d979110a2ab51049d92f408af/packaging-20.9-py2.py3-none-any.whl (40kB)
    100% |████████████████████████████████| 40kB 309kB/s
Collecting typing-extensions>=3.6.4; python_version < "3.8" (from importlib-metadata; python_version < "3.8"->pint->pizero-gpslog)
  Downloading https://files.pythonhosted.org/packages/60/7a/e881b5abb54db0e6e671ab088d079c57ce54e8a01a3ca443f561ccadb37e/typing_extensions-3.7.4.3-py3-none-any.whl
Collecting zipp>=0.5 (from importlib-metadata; python_version < "3.8"->pint->pizero-gpslog)
  Downloading https://files.pythonhosted.org/packages/41/ad/6a4f1a124b325618a7fb758b885b68ff7b058eec47d9220a12ab38d90b1f/zipp-3.4.0-py3-none-any.whl
Collecting pyparsing>=2.0.2 (from packaging->pint->pizero-gpslog)
  Downloading https://files.pythonhosted.org/packages/8a/bb/488841f56197b13700afd5658fc279a2025a39e22449b7cf29864669b15d/pyparsing-2.4.7-py2.py3-none-any.whl (67kB)
    100% |████████████████████████████████| 71kB 249kB/s
Installing collected packages: pillow, typing-extensions, zipp, importlib-metadata, pyparsing, packaging, pint, gpxpy, pizero-gpslog
Successfully installed gpxpy-1.4.2 importlib-metadata-3.4.0 packaging-20.9 pillow-8.1.0 pint-0.16.1 pizero-gpslog-1.1.0 pyparsing-2.4.7 typing-extensions-3.7.4.3 zipp-3.4.0
[2021-01-30 18:25:33,601 INFO] Writing systemd unit file:
[Unit]
Description=pizero-gpslog service
Documentation=https://github.com/jantman/pizero-gpslog
Requires=gpsd.service
After=gpsd.service
AssertArchitecture=arm
[Service]
Type=simple
ExecStart=/usr/bin/python3 /usr/local/bin/pizero-gpslog
WorkingDirectory=/home/pi
User=1000
Group=1000
Environment=OUT_DIR=/home/pi FLUSH_FILE=true GPS_INTERVAL_SEC=5 LOG_LEVEL=WARNING
RestartSec=10
Restart=always
[Install]
WantedBy=default.target
[2021-01-30 18:25:33,627 INFO] systemd unit file written to: /etc/systemd/system/pizero-gpslog.service
[2021-01-30 18:25:33,632 INFO] Running "/usr/bin/systemctl daemon-reload"
[2021-01-30 18:25:39,660 INFO] Running "/usr/bin/systemctl enable pizero-gpslog"
Created symlink /etc/systemd/system/default.target.wants/pizero-gpslog.service → /etc/systemd/system/pizero-gpslog.service.
[2021-01-30 18:25:45,582 INFO] Installation complete. Service enabled.


 pizero-gpslog.service - pizero-gpslog service
   Loaded: loaded (/etc/systemd/system/pizero-gpslog.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Sat 2021-01-30 18:28:48 CET; 5s ago
     Docs: https://github.com/jantman/pizero-gpslog
  Process: 2823 ExecStart=/usr/bin/python3 /usr/local/bin/pizero-gpslog (code=exited, status=1/FAILURE)
 Main PID: 2823 (code=exited, status=1/FAILURE)
 
 Jan 30 18:29:43 pigps systemd[1]: pizero-gpslog.service: Main process exited, code=exited, status=1/FAILURE
Jan 30 18:29:43 pigps systemd[1]: pizero-gpslog.service: Failed with result 'exit-code'.
Jan 30 18:29:43 pigps sudo[3112]:       pi : TTY=pts/0 ; PWD=/home/pi ; USER=root ; COMMAND=/usr/bin/journalctl
Jan 30 18:29:43 pigps sudo[3112]: pam_unix(sudo:session): session opened for user root by pi(uid=0)
Jan 30 18:29:53 pigps systemd[1]: pizero-gpslog.service: Service RestartSec=10s expired, scheduling restart.
Jan 30 18:29:53 pigps systemd[1]: pizero-gpslog.service: Scheduled restart job, restart counter is at 11.
Jan 30 18:29:53 pigps systemd[1]: Stopped pizero-gpslog service.
Jan 30 18:29:53 pigps systemd[1]: Started pizero-gpslog service.
Jan 30 18:29:55 pigps python3[3115]: Traceback (most recent call last):
Jan 30 18:29:55 pigps python3[3115]:   File "/usr/local/bin/pizero-gpslog", line 6, in <module>
Jan 30 18:29:55 pigps python3[3115]:     from pizero_gpslog.runner import main
Jan 30 18:29:55 pigps python3[3115]:   File "/usr/local/lib/python3.7/dist-packages/pizero_gpslog/runner.py", line 51, in <module>
Jan 30 18:29:55 pigps python3[3115]:     from pizero_gpslog.displaymanager import DisplayManager
Jan 30 18:29:55 pigps python3[3115]:   File "/usr/local/lib/python3.7/dist-packages/pizero_gpslog/displaymanager.py", line 45, in <module>
Jan 30 18:29:55 pigps python3[3115]:     from pizero_gpslog.displays.base import BaseDisplay
Jan 30 18:29:55 pigps python3[3115]:   File "/usr/local/lib/python3.7/dist-packages/pizero_gpslog/displays/base.py", line 40, in <module>
Jan 30 18:29:55 pigps python3[3115]:     from PIL import ImageFont
Jan 30 18:29:55 pigps python3[3115]:   File "/usr/local/lib/python3.7/dist-packages/PIL/ImageFont.py", line 34, in <module>
Jan 30 18:29:55 pigps python3[3115]:     from . import Image, features
Jan 30 18:29:55 pigps python3[3115]:   File "/usr/local/lib/python3.7/dist-packages/PIL/Image.py", line 94, in <module>
Jan 30 18:29:55 pigps python3[3115]:     from . import _imaging as core
Jan 30 18:29:55 pigps python3[3115]: ImportError: libopenjp2.so.7: cannot open shared object file: No such file or directory
Jan 30 18:29:55 pigps systemd[1]: pizero-gpslog.service: Main process exited, code=exited, status=1/FAILURE
Jan 30 18:29:55 pigps systemd[1]: pizero-gpslog.service: Failed with result 'exit-code'.

**Comment by edegraaff** [comment]
To test i also installed gpdsd-clients to be able to do some extra tests and cgps -s delivers readings with right coordinates.

**Comment by jantman** [comment]
@edegraaff Ok. Apologies for the delayed response.

The daemon should just start once and stay running. If it's restarting all the time, as shown above, there's something wrong.

Looking at the log, I'm pretty sure I know what's going on. I had to add Pillow, which is a Python image processing library, to support the optional e-ink display. It looks like Pillow has some Raspbian package dependencies, that I forgot to add to the instructions and/or install script.

It looks like the easiest way to fix this on Rasbian 10 is to run:

``sudo apt-get install libjpeg62-turbo libimagequant0 libfreetype6 liblcms2-2 libtiff5 libwebp6 libwebpdemux2 libwebpmux3 libopenjp2-7``

Most of those might already be installed, but that should ensure that all of the dependencies are there, including any that are missing.

Please let me know if that works or not. If it does, I'll get the install script updated accordingly.

**Comment by edegraaff** [comment]
Thanks for you analyse.  In the fututre i will make use of the whole project, and add led's and even maybe a e-inkt device on a nano. In fact in that situation i would make a device with a case and a protected screen otherwise i do expect damage to the screen.  The project is almost in a state you can add a itemlist, and some. 

Afer the suggested exta modules it seem it works as expected. I do have now two .json files in the pi home folder. 
You fixed it :-) 

Later today we will make a short hike, and i put the raspberry model 1 in the backpack with a powerbank and see what we get. 

Regards
Eelco

**Comment by edegraaff** [comment]
If you like i can rebuild the whole with your new disstrubution script  (when you give me the signal to test)  to see if we have a complete and working endproduct.

**Comment by jantman** [comment]
Ok, sounds good! Best of luck!

I've just added ``python3-pillow`` to [Step 8 of the installation instructions](https://github.com/jantman/pizero-gpslog#software-installation); this should be the easiest and most reliable way of ensuring that Pillow and all of its dependencies are installed.
